In [ ]:
#  QUESTION 1 (9 points)
#  -----------------------------------------------------
#  For this assignment we will use a fictional dataset of trader transactions
#  of a stock broker (such as Robinhood). The dataset provides a snapshot of
#  trader transactions for the first months of 2019 and not the whole picture.
#  Meaning, the dataset has both new and existing traders with transactions
#  based on their existing portfolio. Download the dataset from the
#  assignment page. Here is a quick overview of the dataset columns:
#
#    trader_name: full name of each trader
#    phone_numbers: one or two known phone numbers for each trader
#    stock_symbol: code name of a stock
#    stock_name: full name of a stock (usually the stock name)
#    exchange: stock exchange that this stock trades in
#    market_cap: market capitalization for this stock
#    trans_date: date of transaction (purchase or sell of a number of stocks)
#    price_usd: price per stock for that transaction
#    transaction_type: it is either BUY or SELL
#
#  You will notice that there can be multiple transactions per trader, each
#  one recorded on a separate row.
#
#  Design an appropriate 3NF relational schema. Provide either the Python or the R code that
#  connects to the database and creates all necessary tables as per the 3NF relational schema you designed 
#  Note: (you may use either uni_small or uni_large database, or create your own new database using pgAdmin) 
#  Note: (you should create more than one table).
#
#  Important:
#  In your CREATE TABLE statements you must provide data types AND
#  primary/foreign keys (as applicable to relate your schemas).
#
#  NOTE: All actions must be performed in your either Python or R code. No points if the database
#        tables are created manually in pgAdmin and not with either Python or R code.
#
#  Make sure your code has no errors. 
#  When grading, we will run your script and see all the appropriate tables are created in the database properly.
#
#
#	SCORING RUBRIC
#	**************
#	1 points: Necessary packages are imported. Necessary database connections are made.
#	4 points: All necessary tables for 3NF are defined. 
#	3 points: All tables has correct PK/FK as appropriate, and all columns has correct data type, 
#					relevant columns has appropriate NULL / NOT NULL constraints defined.
#	2 points: Simply copy/pasting and executing the script provided in answer-1 
#				creates all tables successfully in the database without any error
#				*1 minor (but only syntax) error will still get you 1 point
#****************************************************************************************************************
# SOLUTION: Question 1
import psycopg2, os
conn = psycopg2.connect(
    host="localhost",
    port='5432',
    database="postgres",
    user="postgres",
    password="123")

cur = conn.cursor()

createCmd = """ CREATE TABLE trader (
                trader_id int PRIMARY KEY,
                trader_name    VARCHAR(30),
                phone_numbers  VARCHAR(20)
                )
            """
    
cur.execute(createCmd)
conn.commit()

createCmd = """ CREATE TABLE stock (
                stock_symbol      VARCHAR(30) PRIMARY KEY,
                stock_name        VARCHAR(30),
                exchange          VARCHAR(10),
                market_cap        NUMERIC
                )
            """
    
cur.execute(createCmd)
conn.commit()

createCmd = """ CREATE TABLE transaction (
                transaction_id SERIAL PRIMARY KEY,
                trans_date        DATE,
                trans_type        VARCHAR(10),
                price_usd         NUMERIC,
                trader_name       VARCHAR(30),
                ticker            VARCHAR(30),
                FOREIGN KEY (trader_name) REFERENCES trader(trader_name),
                FOREIGN KEY (ticker) REFERENCES stock(stock_symbol)
                )
            """
    
cur.execute(createCmd)
conn.commit()

#
#****************************************************************************************************************

In [2]:
import pandas as pd
df = pd.read_csv('/Users/yutingwang/Downloads/HW6_DATA.csv')
print(df)

         trader_name              phone_numbers stock_symbol  \
0       Nerte Ireson  887-162-6610*834-611-0104          MDR
1       Nerte Ireson  887-162-6610*834-611-0104          MDR
2        Dick Treble               883-607-7462         RFDI
3     Monro Westbury  714-486-1867*881-796-0566         MESO
4     Monro Westbury  714-486-1867*881-796-0566         MESO
...              ...                        ...          ...
3582     Gery Dugood  854-830-6040*983-314-1082          AGO
3583     Gery Dugood  854-830-6040*983-314-1082          AGO
3584     Gery Dugood  854-830-6040*983-314-1082          AGO
3585      Customer-1             1-212-212-2211         FAKE
3586      Customer-1             1-212-212-2211         FAKE

                                             stock_name exchange market_cap  \
0                         McDermott International, Inc.     NYSE     $1.78B
1                         McDermott International, Inc.     NYSE     $1.78B
2     First Trust RiverFront Dynamic Developed Inter...   NASDAQ   $199.67M
3                                     Mesoblast Limited   NASDAQ   $654.76M
4                                     Mesoblast Limited   NASDAQ   $654.76M
...                                                 ...      ...        ...
3582                              Assured Guaranty Ltd.     NYSE     $5.11B
3583                              Assured Guaranty Ltd.     NYSE     $5.11B
3584                              Assured Guaranty Ltd.     NYSE     $5.11B
3585                                          Fake Inc.     AMEX      $1.1T
3586                                          Fake Inc.     AMEX      $1.1T

     trans_date trans_type  price_usd
0      7/5/2019        BUY     10.980
1      7/8/2019       SELL     10.872
2      4/8/2019       SELL     69.372
3     6/18/2019       SELL      5.856
4     6/19/2019       SELL      5.700
...         ...        ...        ...
3582   4/3/2019       SELL     54.228
3583   4/4/2019        BUY     54.456
3584   4/5/2019       SELL     54.420
3585  3/11/2019        BUY  90000.000
3586  3/12/2019       SELL  80000.000

[3587 rows x 9 columns]

In [1]:
# -----------------------------------------------------------------------------
#
#  QUESTION 2 (20 points)
#  ------------------------
#  Provide the either Python or R code that populates the database with the data from the
#  provided "HW6_DATA.csv" file. You can download the dataset
#  from the assignment page. It is anticipated that you will perform several steps
#  of data processing in Python or R in order to extract, transform and load all data from
#  the file to the database tables. Manual transformations in a spreadsheet, or
#  similar, are not acceptable, all work must be done in either Python or R. Make sure your code
#  has no errors, no partial credit for code that returns errors. When grading,
#  we will run your script and see all the appropriate data is inserted in correct tables in the database.
#
#	SCORING RUBRIC
#	**************
#	2 points: Necessary packages are imported. Necessary database connections are made.
#	1 points: Code is reading / loading correct data file without any error. 
#	8 points: All 3NF tables are loaded correctly with correct data.
#	4 points: Trader phone numbers are transformed correctly to load in appropriate 3NF table 
#					relevant columns has appropriate NULL / NOT NULL constraints defined.
#	2 points: Apropriate PK values are generated and loaded into tables correctly
#	3 points: Simply copy/pasting and executing the script provided in answer-2 
#				loads all the data successfully in the appropriate tables without any error
#			  *1 minor (but only syntax) error will still get you 1 point


#****************************************************************************************************************
# SOLUTION: Question 2

# Create Table Trader
df.insert(0, 'trader_id', range(1, 1+len(df)))
df['aa'] = df['phone1_and_phone2'].astype(str)
df.phone1_and_phone2.str.split(expand=True,)
df['phone1'] = df['aa'].str[0:12]
df['phone2'] = df['aa'].str[14:]
df.drop('aa',axis = 1, inplace=True)
df.drop('phone1_and_phone2',axis = 1, inplace=True)
trader_df = df[['trader_id','trader_name','phone1','phone2']]
trader_df.to_sql(name='trader',con=engine, if_exists='append', index=False)

# Create Table Stock
stock_df.insert(0,'stock_id',range(1,1+len(drugs_df)))

# Create Table Transaction


#
#****************************************************************************************************************

In [ ]:
# -----------------------------------------------------------------------------
#
#  QUESTION 3
#  ------------------------------------------
#
#	To create data logic abstraction, create all necessary views in the database such that 
#	your answers can use any number of select statements 
#	but can keep those statements as simple as selecting from a view (select * from <your view name>)
#
#****************************************************************************************************************
# SOLUTION: Question 3

#
#****************************************************************************************************************

In [ ]:
# -----------------------------------------------------------------------------
#
#  QUESTION 4
#  ----------------------------------------------------
#
#  Write the Python or R code that queries the database and creates a
#  graph to show how many number (count) of traders traded on each exchange
#	X axis: exchanges
#	Y axis:	count of traders

#	Your answer can use any number of select statements 
#	but should keep those statements as simple as selecting from a view (select * from <your view name>)
#	without additional joins or conditions

#	SCORING RUBRIC
#	**************
#	1 points: Necessary packages are imported. Necessary database connections are made.
#	1 points: Proper axis titles, plot title and legend
#	1 points: Correct database view is correctly used for the purpose
#	3 points: Graph is generated correctly and is showing up correctly by executing the code, 
#				without any manual intervention
#	1 points: Simply copy/pasting and executing the script provided in answer-4 
#				generates the graph correctly
#				*even a minor (including syntax) error will not get you this 1 point

#****************************************************************************************************************
# SOLUTION: Question 4
import numpy as np
from matplotlib import pyplot as plt

#
#****************************************************************************************************************

In [ ]:
# -----------------------------------------------------------------------------
#
#  QUESTION 5 (11 points)
#  ------------------------
#  Write the Python or R code that queries the database and creates a
#  timeseries plot of stock prices, of any one stock_symbol with the most transactions. 
#  If more than one stock_symbol has same most transactions, 
#  then pick the alphabetical first stock_symbol among those.
#  The plot has the following requirements:
#
#	X axis: trans_date
#	Y axis:	price


#   Two timeseries plotted on the same figure:
#     A: standard price of the ticker (solid line, blue color)
#     B: moving average of the price of the same ticker on a 3-day window
#        (dotted line, orange color)
#
#  Result should be one figure, do not produce separate figures.
#
#	SCORING RUBRIC
#	**************
#	1 points: Necessary packages are imported. Necessary database connections are made.
#	3 points: Proper axis titles, plot title and legend. Proper lines in required color 
#	1 points: Correct database view(s) / select statement(s) is/are correctly used for the purpose
#	5 points: Graph is generated correctly and is showing up correctly by executing the code, 
#				without any manual intervention
#	1 points: Simply copy/pasting and executing the script provided in answer
#				generates the graph correctly
#				*even a minor (including syntax) error will not get you this 1 point


#****************************************************************************************************************
# SOLUTION: Question 5

#
#****************************************************************************************************************

In [ ]:
# -----------------------------------------------------------------------------
#
#  QUESTION 6 (0 points - Answer is already provided)
#  -----------------------------------------------------
#
#  Provide either a Python or R code such that if the whole script is executed 
#  once, then ALL the views and tables created by you for this exercise will be deleted in one go wihtout generating any error.
#	Hint: A few objects you have created would have dependencies on other objects you have created
#
#	SCORING RUBRIC
#	**************
#	1 points: Sequence of deletion is correct.
#	2 points: Simply copy/pasting and executing the script provided in answer-6 
#				deletes ALL the database objects created in all the above answeres, without any error
#			*even a minor (including syntax) error will not get you this 1 point
#****************************************************************************************************************
# SOLUTION: Question 6

#
#****************************************************************************************************************

# -----------------------------------------------------------------------------

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import matplotlib.dates as dates

idx = pd.date_range('2011-05-01', '2011-07-01')
s = pd.Series(np.random.randn(len(idx)), index=idx)

fig, ax = plt.subplots()
ax.plot_date(idx.to_pydatetime(), s, 'v-')
ax.xaxis.set_minor_locator(dates.WeekdayLocator(byweekday=(1),
                                                interval=1))
ax.xaxis.set_minor_formatter(dates.DateFormatter('%d\n%a'))
ax.xaxis.grid(True, which="minor")
ax.yaxis.grid()
ax.xaxis.set_major_locator(dates.MonthLocator())
ax.xaxis.set_major_formatter(dates.DateFormatter('\n\n\n%b\n%Y'))
plt.tight_layout()
plt.show()

In [ ]:
'''

Time Series plt show  
samples format: dataframe 
  data['date', 'CBCFI']
  e.g.: 2014-4-28, 715.59
'''
import matplotlib.dates as mdates
from datetime import datetime
import matplotlib.cbook as cbook
import matplotlib.ticker as ticker
fig, axes = plt.subplots( figsize=(12, 6))
data=pd.DataFrame(columns=['date', 'CBCFI'])
data['date']=['2018-7-26','2019-1-4','2019-1-14']
data['date']=pd.to_datetime(data['date'])
data['CBCFI']=[2,3,4]
N = len(data)
ind = np.arange(N)  #数据索引

'''
font
'''
font = {'family' : 'Times New Roman',
'weight' : 'normal',
'size'   : 14,}

date = data.date.astype('O')

test_date = data[(data.date == '2019-1-14')].index.tolist()[0]  
val_date = data[(data.date == '2018-7-26')].index.tolist()[0]  

def format_date(x, pos=None):
    thisind = np.clip(int(x + 0.5), 0, N - 1)
    return date[thisind].strftime('%Y-%m-%d')  #转换时间格式

ax = axes
ax.plot(ind, data.CBCFI, '-' ,linewidth=1)
ax.xaxis.set_major_formatter(ticker.FuncFormatter(format_date))
ax.set_title("CBCFI History Values",font)
fig.autofmt_xdate()  #斜着显示时间戳

'''
设置刻度值的font
'''
plt.tick_params(labelsize=12)
labels = ax.get_xticklabels() + ax.get_yticklabels()
[label.set_fontname('Times New Roman') for label in labels]

'''
插入竖线
'''
axes.axvline(x=val_date, color='g', linewidth=1,linestyle = '-.')
axes.axvline(x=test_date, color='r', linewidth=1,linestyle = ':')

'''
设置横纵坐标的font
'''
plt.ylabel('Index Value', font)
plt.xlabel('Time',font)
plt.autoscale(enable=True, axis='both')

'''
设置图例font
'''
#plt.legend(prop=font)

plt.savefig('F:DataFolder/coal/CBCFI.jpg')
plt.show()

#显示中文
import matplotlib.pyplot as plt

plt.xlabel("x轴") 
plt.ylabel("y轴", fontproperties="SimSun") # 步骤一    （宋体）
plt.title("标题", fontproperties="SimHei") #          （黑体）
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(0, 10, 10)
print(x)
y = x**2
plt.plot(x, y)
# 添加标题plt.title("y = x^2")
# 添加 x 轴的信息
plt.xlabel("x")
# 添加 y 轴的信息
plt.ylabel("y")
# 保存图片plt.savefig('1.jpg')
plt.show()

In [ ]:
data=pd.DataFrame(columns=['date', 'CBCFI'])
data['date']=['2018-7-26','2019-1-4','2019-1-14']
data['date']=pd.to_datetime(data['date'])
data['CBCFI']=[2,3,4]
N = len(data)
ind = np.arange(N)  #数据索引
print(ind)

'''
font
'''
font = {'family' : 'Times New Roman',
'weight' : 'normal',
'size'   : 14,}

date = data.date.astype('O')

test_date = data[(data.date == '2019-1-14')].index.tolist()[0]  
val_date = data[(data.date == '2018-7-26')].index.tolist()[0]  

def format_date(x, pos=None):
    thisind = np.clip(int(x + 0.5), 0, N - 1)
    return date[thisind].strftime('%Y-%m-%d')  #转换时间格式

ax = axes
ax.plot(ind, data.CBCFI, '-' ,linewidth=1)
ax.xaxis.set_major_formatter(ticker.FuncFormatter(format_date))
ax.set_title("CBCFI History Values",font)
fig.autofmt_xdate()  #斜着显示时间戳

'''
设置刻度值的font
'''
plt.tick_params(labelsize=12)
labels = ax.get_xticklabels() + ax.get_yticklabels()
[label.set_fontname('Times New Roman') for label in labels]

'''
插入竖线
'''
axes.axvline(x=val_date, color='g', linewidth=1,linestyle = '-.')
axes.axvline(x=test_date, color='r', linewidth=1,linestyle = ':')

'''
设置横纵坐标的font
'''
plt.ylabel('Index Value', font)
plt.xlabel('Time',font)
plt.autoscale(enable=True, axis='both')

'''
设置图例font
'''
#plt.legend(prop=font)

# plt.savefig('F:DataFolder/coal/CBCFI.jpg')
plt.show()

#显示中文
import matplotlib.pyplot as plt

plt.xlabel("x轴") 
plt.ylabel("y轴", fontproperties="SimSun") # 步骤一    （宋体）
plt.title("标题", fontproperties="SimHei") #          （黑体）
plt.show()